### ISSUE TITLE
[Docs] Revamp

### ISSUE THREAD

**Issue by viktormarinho** [deco-sites/starting#315]
# Docs revamp

<p align="center">
  <img width="300" src="https://github.com/deco-sites/starting/assets/56888067/045a3f66-a723-496c-aad6-819e0649bc61" />
</p>

The Documentation is currently in need of a list of fixes and some rewrites, a lot of it because of our [new admin](https://deco.cx/en/blog/deco-2-0-a-new-era-for-frontend-development)

This Issue will be used to keep track of all the mapped needed changes. Feel free to contribute!

- **Screenshots**: We have a lot of screenshots using the old admin version. We probably want to replace them with the equivalent newer interface or create a nice way for versioning our documentation.
- **Broken images**: There are some images with broken links. need to fix those.
- **Content**:
  - Take time to read and rewrite some part of it, a lot has changed.
  - Would be nice to have short video tutorials on some pages. 
  - I'd like to have a list of all matchers, each with a short video explaining them.
  - Replace any Excalidraw diagram with an on-brand one.
  - New overview page, coming soon

### Task list

- [ ] #333
- [ ] Versioning
- [ ] Update screenshots
- [x] #331
- [ ] Aside height/scroll seems buggy
- [x] #318
- [x] #319
- [ ] Content:
  - [ ] Deco
  - [ ] Deco Basics
  - [ ] Getting started
  - [ ] Sections
  - [ ] Pages
  - [ ] Loaders
  - [ ] Actions
  - [ ] Matchers & Segmentation (With a page and a video for each Matcher that comes by default in the project)
  - [ ] Apps
  - [ ] Themes
  - [ ] #337
  - [ ] Analytics
  - [ ] Tracing
  - [ ] Partials
  - [ ] Async Rendering
  - [ ] Secrets
  - [ ] Performance: (a lot of pages as well)
  - [ ] #329
  - [ ] Admin publish flow, how Deco <> Git works
  - [ ] Admin 2.0: Migration and common problems one could encounter
  - [ ] Developing locally (Env setup, Collaboration)
  - [ ] Roles & Permissions
  - [ ] Examples: Should be present in each of the upper files; and Copy Paste should compile & work for code snippets
  - [ ] Reference
    - [ ] Widgets
    - [ ] Annotations
    - [ ] Errors
    - [ ] Utility Types

**Comment by mcandeia** [comment]
- Fix core web vitals "test" which is a broken link

**Comment by viktormarinho** [comment]
- Shopify docs with broken links

**Comment by matheusgr** [comment]
Revamp in another branch.
